### ISSUE TITLE
[BUG] Request failuje pokud obsahuje krom query i operationName

### ISSUE THREAD

**Issue by HonzaBejvl** [infinityloop-dev/graphpinator#24]
Následující validní request na https://api.nemovizor.cz/ failne:  

`{"query":"query introspection_phase_1 {  schema: __schema {    types    {      name      fields      {        name      }    }  }}","operationName":"introspection_phase_1"}`

Následující request proběhne ok: 

`{"query":"query introspection_phase_1 {  schema: __schema {    types    {      name      fields      {        name      }    }  }}"}`

Pokud nepůjde zreplikovat na lokalu, mohu dodat logy z produkce.

Prosím o zchecknutí, díky.

**Comment by peldax** [comment]
@vossik Pls fix asap
